version : 2.1
default: &default
  machine:
    image: circleci/classic:latest
jobs:
  build:
    <<: *default
    steps:
      - checkout
      - run: sudo sysctl -n -w fs.inotify.max_user_instances=512
      - run: sudo apt-get update
      - run: sudo apt-get install libgdiplus
      - run: bash .sh/install-dotnet.sh
      - run: bash .sh/test.sh
      - run: curl -s https://codecov.io/bash > ./codecov
      - run: chmod +x ./codecov
      - run: ./codecov -f "./src/StorefrontCommunity.Gallery.Tests/coverage/opencover.xml" -t $CODECOV_TOKEN
      - store_artifacts:
          path: src/StorefrontCommunity.Gallery.Tests/coverage/report/summary.htm
          destination: coverage-report.htm
  deploy:
    <<: *default
    steps:
      - checkout
      - run: bash .sh/install-dotnet.sh
      - run: bash .sh/install-docker.sh
      - run: dotnet publish src -c release -o dist
      - run: docker build -t storefront.community/api/gallery:${CIRCLE_TAG/v/} -f Dockerfile .
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_TOKEN
      - run: docker push storefront.community/api/gallery:${CIRCLE_TAG/v/}
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v\d\.\d\.\d/
            branches:
              ignore: /.*/
